name = "PerturbPlasma"
uuid = "68cdf181-988b-4042-8999-0b9541c1c3c2"
authors = ["Mike Petersen <petersen@iap.fr>"]
version = "0.1.0"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[compat]
FastGaussQuadrature = "0.4.2"
julia = "1.5"
