
name: RunBenchmark
on:
  push:

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.7.2
          arch: x64
      - name: instantiate environment
        run: |
            pwd
            julia --project=fht -e '
              using Pkg
              Pkg.add("BenchmarkTools")
              Pkg.add(url="https://github.com/michael-petersen/OrbitalElements.jl.git")
              Pkg.add(url="https://github.com/michael-petersen/FiniteHilbertTransform.jl.git")'
            ls
            julia --project=fht -e '
              using Pkg
              Pkg.develop(PackageSpec(path="/home/runner/work/FiniteHilbertTransform.jl/OrbitalElements.jl"))
              Pkg.develop(PackageSpec(path="/home/runner/work/FiniteHilbertTransform.jl/FiniteHilbertTransform.jl"))'
      - name: benchmark
        run: julia --project=fht examples/run_basetests.jl
